kind: ConfigMap
apiVersion: v1
metadata: 
  name: app-package
data:
  app-package.json: {{ required "A valid .Values.appPackage entry required!" ( tpl ( .Values.appPackage | default ( .Files.Get "files/app-package.json")) . | quote ) }}