
daskWorkerImage: ""

daskGatewayUrl: "http://traefik-dask-gateway.dask-gateway.svc.cluster.local:80"

dockerPull: ""


pvs: 
  storage: 10Gi
  storageClassName: standard


resources:
  limits:
    cpu: "2"
    memory: "1024Mi"
  requests:
    cpu: "1"
    memory: "512Mi"