FROM docker.io/python:3.10-slim-bullseye

RUN apt update && apt-get install -y libexpat1

ADD requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

ENV PYTHONPATH=/app

ADD init-dask.py /app/init-dask.py

ENTRYPOINT []
