kind: ConfigMap
apiVersion: v1
metadata: 
  name: dask-gateway-config
data:
  gateway.yaml: |
      gateway:
        address: "{{ .Values.daskGatewayUrl }}"
                
        cluster:
          options: 
            image: "{{ .Values.daskWorkerImage }}"
            worker_cores: 0.5
            worker_cores_limit: 1
            worker_memory: "4 G"
          

                    